[package]
name = "gbfs-watcher"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.23", default-features = false, features = ["clock"] }
futures = "0.3.25"
reqwest = { version = "0.11.12", features = ["json"] }
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
thiserror = "1.0.37"
tokio = { version = "1.21.2", features = ["macros", "fs", "sync", "io-util", "time"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
