name: Build and publish Docker image

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"

env:
  DOCKER_IMAGE_BASENAME: ghcr.io/remi-dupre/gbfs-watcher

jobs:
  build_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: gbfs-watcher

      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          context: .
          push: true
