name: Build and publish Docker image

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"

env:
  DOCKER_IMAGE_BASENAME: ghcr.io/remi-dupre/gbfs-watcher

jobs:
  build_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get image name
        run: |
          VERSION=${GITHUB_REF#refs/*/}
          if [ "$VERSION" == "main" ]; then
            IMAGE_TAG=latest
          else
            IMAGE_TAG=$VERSION
          fi
          echo "DOCKER_IMAGE=$DOCKER_IMAGE_BASENAME:$IMAGE_TAG" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug

      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          tags: ${{ env.DOCKER_IMAGE }}
          labels: "org.label-schema.vcs-ref=${{ github.sha }}"
          platforms: linux/amd64,linux/arm64
          context: .
          push: true
